#!/usr/bin/env bash
# tools/ollama/generate_md.sh
# Generate a Markdown document from an Ollama prompt and save to docs/
# Usage: ./generate_md.sh -p prompt-file -o output-file -m model -h host

set -euo pipefail

function usage() {
  cat <<EOF
Usage: $0 -p PROMPT_FILE -o OUTPUT_FILE [-m MODEL] [-h HOST]

Reads the prompt from PROMPT_FILE (or stdin if -p is '-') and calls the Ollama
local API to generate text. The result will be written to OUTPUT_FILE (path
created if necessary). ENV:
  OLLAMA_HOST (overridden by -h)
  OLLAMA_MODEL (overridden by -m)

Example:
  ./tools/ollama/generate_md.sh -p tools/ollama/prompts/example_prompt.txt -o docs/ollama-summary.md
EOF
}

PROMPT_FILE=""
OUTPUT_FILE=""
MODEL="${OLLAMA_MODEL:-qwen2.5-coder:14b-instruct-q4_0}"
HOST="${OLLAMA_HOST:-http://127.0.0.1:11434}"

while getopts ":p:o:m:h:" opt; do
  case ${opt} in
    p ) PROMPT_FILE="$OPTARG" ;;
    o ) OUTPUT_FILE="$OPTARG" ;;
    m ) MODEL="$OPTARG" ;;
    h ) HOST="$OPTARG" ;;
    \? ) usage; exit 1 ;;
  esac
done

if [ -z "$PROMPT_FILE" ] || [ -z "$OUTPUT_FILE" ]; then
  usage
  exit 1
fi

if [ "$PROMPT_FILE" = "-" ]; then
  PROMPT=$(cat -)
else
  if [ ! -f "$PROMPT_FILE" ]; then
    echo "Prompt file not found: $PROMPT_FILE" >&2
    exit 2
  fi
  PROMPT=$(cat "$PROMPT_FILE")
fi

# Ensure output dir exists
mkdir -p "$(dirname "$OUTPUT_FILE")"

# Call the local Ollama HTTP API. This uses the saimplest possible payload and
# tries to extract readable text. Adjust accordingly for non-JSON or streaming
# responses.

RESP_JSON=$(curl -sS -X POST "$HOST/api/generate" \
  -H "Content-Type: application/json" \
  -d "$(jq -n --arg model "$MODEL" --arg prompt "$PROMPT" '{model:$model, prompt:$prompt, stream:false}')" )

# Try to extract 'results[0].content[0].text' or fallback to raw body
CONTENT=$(echo "$RESP_JSON" | jq -r '.results[0].content[0].text // .text // .output // empty')
if [ -z "$CONTENT" ]; then
  # Fallback: pretty-print the JSON response
  CONTENT="\n\n<pre>$(echo "$RESP_JSON" | jq -C .)</pre>\n"
fi

# Write Markdown file with metadata header
cat > "$OUTPUT_FILE" <<EOF
<!-- Generated by tools/ollama/generate_md.sh -->

---
model: "$MODEL"
host: "$HOST"
generated_at: "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
---

**Prompt**:

">
$(echo "$PROMPT" | sed 's/^/> /')

---

**LLM Output**:

$CONTENT
EOF

echo "Wrote $OUTPUT_FILE"
