//! Autogenerated weights for pallet_swarm_evolution
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2025-01-01, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `atlas-sphere`, CPU: `Intel(R) Xeon(R) CPU @ 2.80GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/atlas-sphere-node
// benchmark
// pallet
// --chain=dev
// --steps=20
// --repeat=10
// --pallet=pallet_swarm_evolution
// --extrinsic=*
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./pallets/swarm-evolution/src/weights.rs
// --template=./frame/benchmarking/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{
	traits::Get,
	weights::{Weight, constants::RocksDbWeight as DbWeight},
};
use core::marker::PhantomData;

/// Weight functions needed for pallet_swarm_evolution.
pub trait WeightInfo {
	fn spawn_agent() -> Weight;
	fn mutate_agent() -> Weight;
	fn terminate_agent() -> Weight;
	fn evolve_population() -> Weight;
	fn update_config() -> Weight;
}

/// Weights for pallet_swarm_evolution using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `SwarmEvolution::OwnerAgents` (r:1 w:1)
	/// Proof: `SwarmEvolution::OwnerAgents` (`max_values`: None, `max_size`: Some(4350), added: 6825, mode: `MaxEncodedLen`)
	/// Storage: `SwarmEvolution::PopulationStats` (r:1 w:1)
	/// Proof: `SwarmEvolution::PopulationStats` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	/// Storage: `SwarmEvolution::AgentPool` (r:0 w:1)
	/// Proof: `SwarmEvolution::AgentPool` (`max_values`: None, `max_size`: Some(1624), added: 4099, mode: `MaxEncodedLen`)
	/// Storage: `SwarmEvolution::AgentCounter` (r:1 w:1)
	/// Proof: `SwarmEvolution::AgentCounter` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `SwarmEvolution::EvolutionParameters` (r:1 w:0)
	/// Proof: `SwarmEvolution::EvolutionParameters` (`max_values`: Some(1), `max_size`: Some(10), added: 505, mode: `MaxEncodedLen`)
	fn spawn_agent() -> Weight {
		Weight::from_parts(68_750_000, 12368)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `SwarmEvolution::AgentPool` (r:1 w:1)
	/// Proof: `SwarmEvolution::AgentPool` (`max_values`: None, `max_size`: Some(1624), added: 4099, mode: `MaxEncodedLen`)
	/// Storage: `PopulationStats` (r:1 w:1)
	/// Proof: `PopulationStats` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	fn mutate_agent() -> Weight {
		Weight::from_parts(61_250_000, 4634)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `SwarmEvolution::AgentPool` (r:1 w:1)
	/// Proof: `SwarmEvolution::AgentPool` (`max_values`: None, `max_size`: Some(1624), added: 4099, mode: `MaxEncodedLen`)
	/// Storage: `SwarmEvolution::OwnerAgents` (r:1 w:1)
	/// Proof: `SwarmEvolution::OwnerAgents` (`max_values`: None, `max_size`: Some(4350), added: 6825, mode: `MaxEncodedLen`)
	/// Storage: `PopulationStats` (r:1 w:1)
	/// Proof: `PopulationStats` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	fn terminate_agent() -> Weight {
		Weight::from_parts(90_000_000, 11459)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `SwarmEvolution::AgentPool` (r:501 w:50)
	/// Proof: `SwarmEvolution::AgentPool` (`max_values`: None, `max_size`: Some(1624), added: 4099, mode: `MaxEncodedLen`)
	/// Storage: `PopulationStats` (r:1 w:1)
	/// Proof: `PopulationStats` (`max_values`: Some(1), `max_size`: Some(40), added: 535, mode: `MaxEncodedLen`)
	fn evolve_population() -> Weight {
		Weight::from_parts(500_000_000, 204_510)
			.saturating_add(T::DbWeight::get().reads(502_u64))
			.saturating_add(T::DbWeight::get().writes(51_u64))
	}
	/// Storage: `SwarmEvolution::EvolutionParameters` (r:0 w:1)
	/// Proof: `SwarmEvolution::EvolutionParameters` (`max_values`: Some(1), `max_size`: Some(10), added: 505, mode: `MaxEncodedLen`)
	fn update_config() -> Weight {
		Weight::from_parts(15_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests, implement the old interface.
impl WeightInfo for () {
	fn spawn_agent() -> Weight {
		Weight::from_parts(68_750_000, 12368)
	}
	fn mutate_agent() -> Weight {
		Weight::from_parts(61_250_000, 4634)
	}
	fn terminate_agent() -> Weight {
		Weight::from_parts(90_000_000, 11459)
	}
	fn evolve_population() -> Weight {
		Weight::from_parts(500_000_000, 204_510)
	}
	fn update_config() -> Weight {
		Weight::from_parts(15_000_000, 0)
	}
}
