#![cfg_attr(not(feature = "std"), no_std)]
#![recursion_limit = "256"]

// Required for impl_runtime_apis! macro in no_std
#[cfg(not(feature = "std"))]
extern crate alloc;

use codec::{Decode, Encode};
use frame_support::weights::Weight;
pub use frame_support::{
    construct_runtime, parameter_types,
    traits::{ConstBool, ConstU16, ConstU32, ConstU64, ConstU8, Everything},
    weights::{
        constants::{
            BlockExecutionWeight, ExtrinsicBaseWeight, RocksDbWeight, WEIGHT_REF_TIME_PER_SECOND,
        },
        ConstantMultiplier, IdentityFee,
    },
};
use frame_system::limits;
use pallet_atlas_kernel;
use pallet_audit_governance;
use pallet_aura;
use pallet_balances;
use pallet_collective;
use pallet_grandpa;
use pallet_invariants;
#[cfg(feature = "dev")]
use pallet_sudo;
use pallet_swarm_evolution;
// use pallet_swarm_media;  // TODO: has compilation issues
use pallet_timestamp;
use pallet_transaction_payment::FungibleAdapter;
use scale_info::TypeInfo;
// TODO: Update pallet-botchain-commandments to stable2412 before re-enabling
// use pallet_botchain_commandments;

// Swarm Event Types for Block Metadata
#[derive(Clone, Debug, Eq, PartialEq, Encode, Decode, TypeInfo)]
pub enum SwarmEvent<AccountId> {
    /// Agent was born (agent_id, parent_id, job_type, birth_data)
    AgentBorn(Vec<u8>, Option<Vec<u8>>, u8, Vec<u8>),
    /// Agent died (agent_id, reason, final_score)
    AgentDied(Vec<u8>, Vec<u8>, u32),
    /// Agent evolved (agent_id, old_tier, new_tier, evolution_data)
    AgentEvolved(Vec<u8>, u8, u8, Vec<u8>),
    /// Content generated (content_id, agent_id, platform, quality_score)
    ContentGenerated(Vec<u8>, Vec<u8>, Vec<u8>, u32),
    /// Content published (content_id, platform, url, engagement_initial)
    ContentPublished(Vec<u8>, Vec<u8>, Vec<u8>, u64),
    /// Job completed (job_id, agent_id, reward_earned, performance_score)
    JobCompleted(Vec<u8>, Vec<u8>, u128, u32),
    /// Swarm governance action (action_type, proposal_id, result)
    GovernanceAction(Vec<u8>, Vec<u8>, bool),
    /// Economic event (event_type, amount, participants)
    EconomicEvent(Vec<u8>, u128, Vec<AccountId>),
    /// Security event (event_type, severity, details)
    SecurityEvent(Vec<u8>, u8, Vec<u8>),
    /// Evolution event (mutation_id, success, impact_score)
    EvolutionEvent(Vec<u8>, bool, i32),
}
use sp_api::impl_runtime_apis;
use sp_core::OpaqueMetadata;
use sp_core::H256;
use sp_runtime::{
    generic, impl_opaque_keys,
    traits::{AccountIdLookup, BlakeTwo256, Block as BlockT, IdentifyAccount, Verify},
    MultiAddress, MultiSignature, Perbill,
};
use sp_session::{GetSessionNumber, GetValidatorCount};
use sp_std::prelude::*;

#[cfg(any(feature = "std", test))]
pub use sp_runtime::BuildStorage;

// VM Adapters module - provides real VM execution when features enabled
mod vm_adapters;
pub use vm_adapters::{RealEvmAdapter, RealSvmAdapter, RealX3Adapter};

// WASM binary generated by substrate-wasm-builder
#[cfg(feature = "std")]
include!(concat!(env!("OUT_DIR"), "/wasm_binary.rs"));

// When building without std, provide empty binary
#[cfg(not(feature = "std"))]
pub const WASM_BINARY: Option<&[u8]> = None;
#[cfg(not(feature = "std"))]
pub const WASM_BINARY_BLOATY: Option<&[u8]> = None;

/// Opaque types used by the CLI commands.
pub mod opaque {
    use super::*;

    pub type BlockNumber = super::BlockNumber;
    pub type Header = generic::Header<BlockNumber, BlakeTwo256>;
    pub type UncheckedExtrinsic = sp_runtime::OpaqueExtrinsic;
    pub type Block = generic::Block<Header, UncheckedExtrinsic>;
    pub type BlockId = generic::BlockId<Block>;

    impl_opaque_keys! {
        pub struct SessionKeys {
            pub aura: Aura,
            pub grandpa: Grandpa,
        }
    }
}

pub type BlockNumber = u32;
pub type Index = u32;
pub type Signature = MultiSignature;
pub type Hash = H256;
pub type Moment = u64;
pub type Balance = u128;
pub type AssetId = u32;
pub type AtlasId = H256;
pub type Address = MultiAddress<AccountId, ()>;
pub type AccountId = <<Signature as Verify>::Signer as IdentifyAccount>::AccountId;

pub const MILLISECS_PER_BLOCK: u64 = 6_000;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn constants_are_sane() {
        assert_eq!(MILLISECS_PER_BLOCK, 6_000);
    }
}

pub struct RuntimeVersion;
impl frame_support::traits::Get<sp_version::RuntimeVersion> for RuntimeVersion {
    fn get() -> sp_version::RuntimeVersion {
        VERSION
    }
}
pub const SLOT_DURATION: u64 = MILLISECS_PER_BLOCK;

pub const NANO_ATLAS: Balance = 1;
pub const MICRO_ATLAS: Balance = 1_000 * NANO_ATLAS;
pub const MILLI_ATLAS: Balance = 1_000 * MICRO_ATLAS;
pub const ATLAS: Balance = 1_000 * MILLI_ATLAS;

#[sp_version::runtime_version]
pub const VERSION: sp_version::RuntimeVersion = sp_version::RuntimeVersion {
    spec_name: sp_std::borrow::Cow::Borrowed("atlas-sphere"),
    impl_name: sp_std::borrow::Cow::Borrowed("atlas-sphere"),
    authoring_version: 1,
    spec_version: 1,
    impl_version: 1,
    apis: RUNTIME_API_VERSIONS,
    transaction_version: 1,
    system_version: 1,
};

parameter_types! {
    pub const BlockHashCount: BlockNumber = 2_400;
    pub const SS58Prefix: u16 = 42;
    pub const MinimumPeriod: Moment = (MILLISECS_PER_BLOCK / 2) as Moment;
    pub const ExistentialDeposit: Balance = 100 * MICRO_ATLAS;
    pub const TransactionByteFee: Balance = 10 * MICRO_ATLAS;
    pub const MaxAssetsPerAccount: u32 = 32;
    pub const MaxAssetSymbolLength: u32 = 16;
    pub const MaxPayloadLength: u32 = 32 * 1024;
    pub const MaxEvmPayloadLength: u32 = 16 * 1024;  // 16 KB for EVM payloads
    pub const MaxSvmPayloadLength: u32 = 16 * 1024;  // 16 KB for SVM payloads
    pub const MaxCombinedPayloadLength: u32 = 32 * 1024;  // 32 KB combined limit
    pub const MaxAuthorities: u32 = 100;  // Maximum 100 authorities
    pub const MinAuthorities: u32 = 1;  // Minimum 1 authority required
    pub BlockWeights: limits::BlockWeights = limits::BlockWeights::with_sensible_defaults(
        Weight::from_parts(12 * WEIGHT_REF_TIME_PER_SECOND, 5 * 1024 * 1024),
        Perbill::from_percent(75),
    );
    pub BlockLength: limits::BlockLength = limits::BlockLength::max_with_normal_ratio(
        5 * 1024 * 1024,
        Perbill::from_percent(75),
    );
}

#[cfg(feature = "std")]
pub fn native_version() -> sp_version::NativeVersion {
    sp_version::NativeVersion {
        runtime_version: VERSION,
        can_author_with: Default::default(),
    }
}

parameter_types! {
    pub const MaxSetIdSessionEntries: u64 = 0;
    pub const OperationalFeeMultiplier: u8 = 5;
}

parameter_types! {
    pub const CouncilMotionDuration: BlockNumber = 3 * 24 * 60 * 60 / (MILLISECS_PER_BLOCK as BlockNumber / 1000);
    pub const CouncilMaxProposals: u32 = 100;
    pub const CouncilMaxMembers: u32 = 100;
    pub MaxProposalWeight: Weight = Perbill::from_percent(50) * BlockWeights::get().max_block;
}

construct_runtime!(
    pub enum Runtime
    {
        System: frame_system,
        Timestamp: pallet_timestamp,
        Aura: pallet_aura,
        Grandpa: pallet_grandpa,
        Balances: pallet_balances,
        TransactionPayment: pallet_transaction_payment,
        AtlasKernel: pallet_atlas_kernel,
        AuditGovernance: pallet_audit_governance,
        Invariants: pallet_invariants,
        SwarmMedia: pallet_swarm_media,
        SwarmEvolution: pallet_swarm_evolution,
        // TODO: Re-enable after updating to stable2412
        // BotChainCommandments: pallet_botchain_commandments,
        Council: pallet_collective::<Instance1>,
    }
);

pub type Header = generic::Header<BlockNumber, BlakeTwo256>;
pub type UncheckedExtrinsic =
    generic::UncheckedExtrinsic<Address, RuntimeCall, Signature, SignedExtra>;
pub type Block = generic::Block<Header, UncheckedExtrinsic>;
pub type Executive = frame_executive::Executive<
    Runtime,
    Block,
    frame_system::ChainContext<Runtime>,
    Runtime,
    AllPalletsWithSystem,
>;

impl_opaque_keys! {
    pub struct SessionKeys {
        pub aura: Aura,
    }
}

pub type SignedExtra = (
    frame_system::CheckNonZeroSender<Runtime>,
    frame_system::CheckSpecVersion<Runtime>,
    frame_system::CheckTxVersion<Runtime>,
    frame_system::CheckGenesis<Runtime>,
    frame_system::CheckEra<Runtime>,
    frame_system::CheckNonce<Runtime>,
    frame_system::CheckWeight<Runtime>,
    pallet_transaction_payment::ChargeTransactionPayment<Runtime>,
);

pub type SignedPayload = generic::SignedPayload<RuntimeCall, SignedExtra>;

// ===== Config Impls (after construct_runtime!) =====

// Fee handling for FungibleAdapter - uses the new fungible trait's Credit type
use frame_support::traits::fungible::Credit;

pub struct DealWithFees;
impl frame_support::traits::OnUnbalanced<Credit<AccountId, Balances>> for DealWithFees {
    fn on_unbalanced(amount: Credit<AccountId, Balances>) {
        // For now, just drop the fees (burn them)
        // In production, this could be sent to treasury
        drop(amount);
    }
}

impl frame_system::Config for Runtime {
    type BaseCallFilter = Everything;
    type Block = Block;
    type BlockWeights = BlockWeights;
    type BlockLength = BlockLength;
    type DbWeight = RocksDbWeight;
    type RuntimeOrigin = RuntimeOrigin;
    type RuntimeCall = RuntimeCall;
    type Hash = Hash;
    type Hashing = BlakeTwo256;
    type AccountId = AccountId;
    type Lookup = AccountIdLookup<AccountId, ()>;
    type RuntimeEvent = RuntimeEvent;
    type BlockHashCount = BlockHashCount;
    type Version = RuntimeVersion;
    type PalletInfo = PalletInfo;
    type AccountData = pallet_balances::AccountData<Balance>;
    type OnNewAccount = ();
    type OnKilledAccount = ();
    type SystemWeightInfo = frame_system::weights::SubstrateWeight<Runtime>;
    type SS58Prefix = ConstU16<42>;
    type OnSetCode = ();
    type MaxConsumers = ConstU32<16>;
    type Nonce = Index;
    type RuntimeTask = ();
    type ExtensionsWeightInfo = ();
    type SingleBlockMigrations = ();
    type MultiBlockMigrator = ();
    type PreInherents = ();
    type PostInherents = ();
    type PostTransactions = ();
}

impl pallet_timestamp::Config for Runtime {
    type Moment = Moment;
    type OnTimestampSet = ();
    type MinimumPeriod = MinimumPeriod;
    type WeightInfo = ();
}

impl pallet_aura::Config for Runtime {
    type AuthorityId = sp_consensus_aura::sr25519::AuthorityId;
    type MaxAuthorities = MaxAuthorities;
    type DisabledValidators = ();
    type AllowMultipleBlocksPerSlot = ConstBool<false>;
    type SlotDuration = pallet_aura::MinimumPeriodTimesTwo<Runtime>;
}

impl pallet_grandpa::Config for Runtime {
    type RuntimeEvent = RuntimeEvent;
    type KeyOwnerProof = SessionHandler;
    type EquivocationReportSystem = ();
    type WeightInfo = ();
    type MaxAuthorities = MaxAuthorities;
    type MaxSetIdSessionEntries = MaxSetIdSessionEntries;
    type MaxNominators = ConstU32<0>;
}

impl pallet_balances::Config for Runtime {
    type Balance = Balance;
    type DustRemoval = ();
    type RuntimeEvent = RuntimeEvent;
    type ExistentialDeposit = ExistentialDeposit;
    type AccountStore = System;
    type MaxLocks = ConstU32<50>;
    type MaxReserves = ConstU32<50>;
    type MaxFreezes = ConstU32<0>;
    type ReserveIdentifier = [u8; 8];
    type FreezeIdentifier = ();
    type WeightInfo = pallet_balances::weights::SubstrateWeight<Runtime>;
    type RuntimeHoldReason = ();
    type RuntimeFreezeReason = ();
    type DoneSlashHandler = ();
}

impl pallet_transaction_payment::Config for Runtime {
    type RuntimeEvent = RuntimeEvent;
    type OnChargeTransaction = FungibleAdapter<Balances, DealWithFees>;
    type OperationalFeeMultiplier = OperationalFeeMultiplier;
    type WeightToFee = IdentityFee<Balance>;
    type LengthToFee = ConstantMultiplier<Balance, TransactionByteFee>;
    type FeeMultiplierUpdate = ();
    type WeightInfo = pallet_transaction_payment::weights::SubstrateWeight<Runtime>;
}

impl pallet_invariants::Config for Runtime {
    type RuntimeEvent = RuntimeEvent;
    type Currency = Balances;
}

#[cfg(feature = "dev")]
impl pallet_sudo::Config for Runtime {
    type RuntimeEvent = RuntimeEvent;
    type RuntimeCall = RuntimeCall;
    type WeightInfo = pallet_sudo::weights::SubstrateWeight<Runtime>;
}

pub type EnsureRootOrHalfCouncil = frame_support::traits::EitherOfDiverse<
    frame_system::EnsureRoot<AccountId>,
    pallet_collective::EnsureProportionAtLeast<AccountId, CouncilCollective, 1, 2>,
>;

// VM Adapters: Use real implementations from vm_adapters module
// These automatically fall back to deterministic mocks for WASM builds,
// and use real EVM/SVM/X3 execution for native builds with real-* features
pub type RuntimeEvmAdapter = RealEvmAdapter;
pub type RuntimeSvmAdapter = RealSvmAdapter;
pub type RuntimeX3Adapter = RealX3Adapter;

parameter_types! {
    pub const MaxX3PayloadLength: u32 = 16 * 1024;
    pub const MaxCombinedPayloadLengthV2: u32 = 48 * 1024;
    pub const DefaultEvmGasLimit: u64 = 15_000_000;
    pub const DefaultSvmComputeLimit: u64 = 200_000;
    pub const DefaultX3GasLimit: u64 = 10_000_000;
    pub const MaxHtlcPreimageLength: u32 = 32 * 1024;  // 32 KB max HTLC preimage size
}

pub type CouncilCollective = pallet_collective::Instance1;
impl pallet_collective::Config<CouncilCollective> for Runtime {
    type RuntimeOrigin = RuntimeOrigin;
    type Proposal = RuntimeCall;
    type RuntimeEvent = RuntimeEvent;
    type MotionDuration = CouncilMotionDuration;
    type MaxProposals = CouncilMaxProposals;
    type MaxMembers = CouncilMaxMembers;
    type DefaultVote = pallet_collective::PrimeDefaultVote;
    type WeightInfo = pallet_collective::weights::SubstrateWeight<Runtime>;
    type SetMembersOrigin = frame_system::EnsureRoot<AccountId>;
    type MaxProposalWeight = MaxProposalWeight;
    type DisapproveOrigin = frame_system::EnsureRoot<AccountId>;
    type KillOrigin = frame_system::EnsureRoot<AccountId>;
    type Consideration = ();
}

impl pallet_atlas_kernel::Config for Runtime {
    type RuntimeEvent = RuntimeEvent;
    type Balance = Balance;
    type AssetId = AssetId;
    type AtlasId = AtlasId;
    type MaxAssetsPerAccount = MaxAssetsPerAccount;
    type MaxAssetSymbolLength = MaxAssetSymbolLength;
    type MaxEvmPayloadLength = MaxEvmPayloadLength;
    type MaxSvmPayloadLength = MaxSvmPayloadLength;
    type MaxX3PayloadLength = MaxX3PayloadLength;
    type MaxCombinedPayloadLength = MaxCombinedPayloadLength;
    type MaxCombinedPayloadLengthV2 = MaxCombinedPayloadLengthV2;
    type MaxAuthorities = MaxAuthorities;
    type MinAuthorities = MinAuthorities;
    type DefaultEvmGasLimit = DefaultEvmGasLimit;
    type DefaultSvmComputeLimit = DefaultSvmComputeLimit;
    type DefaultX3GasLimit = DefaultX3GasLimit;
    type MaxHtlcPreimageLength = MaxHtlcPreimageLength;
    type WeightInfo = ();
    type Currency = Balances;
    type EvmAdapter = RuntimeEvmAdapter;
    type SvmAdapter = RuntimeSvmAdapter;
    type X3Adapter = RuntimeX3Adapter;
    type GovernanceOrigin = EnsureRootOrHalfCouncil;
}

parameter_types! {
    /// Maximum number of audit artifacts to store on-chain
    pub const MaxAuditArtifacts: u32 = 10000;
    /// Maximum findings per audit
    pub const MaxFindings: u32 = 1000;
    /// Appeal period (14 days = 201600 blocks at 6s blocks)
    pub const AuditAppealPeriod: BlockNumber = 201600;
    /// Override threshold (percent, 0-100)
    pub const OverrideThreshold: u32 = 67;
    /// Governance timelock (2 hours = 1200 blocks at 6s blocks)
    pub const GovernanceTimelock: BlockNumber = 1200;
}

impl pallet_audit_governance::Config for Runtime {
    type RuntimeEvent = RuntimeEvent;
    type MaxAuditArtifacts = MaxAuditArtifacts;
    type MaxFindings = MaxFindings;
    type AuditAppealPeriod = AuditAppealPeriod;
    type OverrideThreshold = OverrideThreshold;
    type GovernanceTimelock = GovernanceTimelock;
    type WeightInfo = pallet_audit_governance::weights::SubstrateWeight<Runtime>;
}

impl pallet_swarm_media::Config for Runtime {
    type RuntimeEvent = RuntimeEvent;
}

parameter_types! {
    /// Maximum agents per owner
    pub const MaxAgentsPerOwner: u32 = 10;
}

impl pallet_swarm_evolution::Config for Runtime {
    type RuntimeEvent = RuntimeEvent;
    type Hashing = BlakeTwo256;
    type MaxAgentsPerOwner = MaxAgentsPerOwner;
    type WeightInfo = pallet_swarm_evolution::weights::SubstrateWeight<Runtime>;
}

parameter_types! {
    /// Maximum number of violation reports that can be stored
    pub const MaxViolationReports: u32 = 1000;
}

// TODO: Re-enable after updating pallet-botchain-commandments to stable2412
// impl pallet_botchain_commandments::Config for Runtime {
// 	type RuntimeEvent = RuntimeEvent;
// 	type Currency = Balances;
// 	type MaxViolationReports = MaxViolationReports;
// 	type SecurityCouncil = EnsureRootOrHalfCouncil;
// }

// Session trait implementations for minimal runtime
#[derive(Debug, Clone, Copy, PartialEq, Eq, Encode, Decode, TypeInfo)]
pub struct SessionHandler;

impl GetValidatorCount for SessionHandler {
    fn validator_count(&self) -> u32 {
        0
    }
}

impl GetSessionNumber for SessionHandler {
    fn session(&self) -> u32 {
        0
    }
}

// sp_session::Config not available in polkadot-v1.0.0
// impl sp_session::Config for Runtime {}

// sp_session::SessionKeys trait has incompatible signatures in polkadot-v1.0.0
/*
impl sp_session::SessionKeys<Block> for Runtime {
    fn generate_session_keys(seed: Option<Vec<u8>>) -> Vec<u8> {
        SessionKeys::generate(seed)
    }

    fn decode_session_keys(encoded: Vec<u8>) -> Option<Vec<(Vec<u8>, sp_core::crypto::KeyTypeId)>> {
        SessionKeys::decode_into_raw_public_keys(&encoded)
    }
}
*/

impl_runtime_apis! {
    impl sp_api::Core<Block> for Runtime {
        fn version() -> sp_version::RuntimeVersion {
            VERSION
        }

        fn execute_block(block: Block) {
            Executive::execute_block(block);
        }

        fn initialize_block(header: &<Block as BlockT>::Header) -> sp_runtime::ExtrinsicInclusionMode {
            Executive::initialize_block(header)
        }
    }

    impl sp_api::Metadata<Block> for Runtime {
        fn metadata() -> OpaqueMetadata {
            OpaqueMetadata::new(Runtime::metadata().into())
        }

        fn metadata_at_version(version: u32) -> Option<OpaqueMetadata> {
            Runtime::metadata_at_version(version)
        }

        fn metadata_versions() -> sp_std::vec::Vec<u32> {
            Runtime::metadata_versions()
        }
    }

    impl sp_transaction_pool::runtime_api::TaggedTransactionQueue<Block> for Runtime {
        fn validate_transaction(
            source: sp_runtime::transaction_validity::TransactionSource,
            tx: <Block as BlockT>::Extrinsic,
            block_hash: <Block as BlockT>::Hash,
        ) -> sp_runtime::transaction_validity::TransactionValidity {
            Executive::validate_transaction(source, tx, block_hash)
        }
    }

    impl sp_session::SessionKeys<Block> for Runtime {
        fn generate_session_keys(seed: Option<Vec<u8>>) -> Vec<u8> {
            opaque::SessionKeys::generate(seed)
        }

        fn decode_session_keys(
            encoded: Vec<u8>,
        ) -> Option<Vec<(Vec<u8>, sp_core::crypto::KeyTypeId)>> {
            opaque::SessionKeys::decode_into_raw_public_keys(&encoded)
        }
    }

    impl sp_genesis_builder::GenesisBuilder<Block> for Runtime {
        fn build_state(json: Vec<u8>) -> sp_genesis_builder::Result {
            frame_support::genesis_builder_helper::build_state::<RuntimeGenesisConfig>(json)
        }

        fn get_preset(id: &Option<sp_genesis_builder::PresetId>) -> Option<Vec<u8>> {
            frame_support::genesis_builder_helper::get_preset::<RuntimeGenesisConfig>(id, |_| None)
        }

        fn preset_names() -> Vec<sp_genesis_builder::PresetId> {
            Vec::new()
        }
    }

    impl pallet_atlas_kernel::AtlasKernelRuntimeApi<Block, AccountId, Balance, AssetId> for Runtime {
        fn get_canonical_balance(account: AccountId, asset_id: AssetId) -> Balance {
            pallet_atlas_kernel::CanonicalLedger::<Runtime>::get(&account, &asset_id)
        }

        fn get_asset_metadata(asset_id: AssetId) -> Option<(Vec<u8>, u8)> {
            pallet_atlas_kernel::AssetRegistry::<Runtime>::get(&asset_id)
                .map(|metadata| (metadata.symbol.into_inner(), metadata.decimals))
        }

        fn is_authorized(account: AccountId) -> bool {
            pallet_atlas_kernel::AuthorizedAccounts::<Runtime>::contains_key(&account)
        }

        fn get_authorized_accounts() -> Vec<AccountId> {
            pallet_atlas_kernel::AuthorizedAccounts::<Runtime>::iter_keys().collect()
        }

        fn get_authorities() -> Vec<AccountId> {
            pallet_atlas_kernel::Authorities::<Runtime>::get().into_inner()
        }

        fn map_evm_address(_address: Vec<u8>) -> Option<AccountId> {
            // EVM integration disabled - return None for all address mappings
            None
        }

        fn get_evm_balance(_evm_address: Vec<u8>, _asset_id: AssetId) -> Option<Balance> {
            // EVM integration disabled - return None for all balance queries
            None
        }

        fn get_evm_code(_evm_address: Vec<u8>) -> Vec<u8> {
            // EVM integration disabled - return empty bytecode
            Vec::new()
        }

        fn get_evm_storage(_evm_address: Vec<u8>, _storage_key: H256) -> Option<H256> {
            // EVM integration disabled - return None for all storage queries
            None
        }
    }

    // impl pallet_swarm_media::SwarmMediaRuntimeApi<Block, AccountId> for Runtime {  // TODO: has compilation issues
    //     fn get_media_status() -> pallet_swarm_media::MediaProductionStatus {
    //         pallet_swarm_media::Pallet::<Runtime>::get_media_status()
    //     }
    //
    //     fn get_contributor(account: AccountId) -> Option<pallet_swarm_media::Contributor> {
    //         pallet_swarm_media::Pallet::<Runtime>::get_contributor(&account)
    //     }
    //
    //     fn get_job(job_id: Vec<u8>) -> Option<pallet_swarm_media::JobStatusRecord> {
    //         pallet_swarm_media::Pallet::<Runtime>::get_job(&job_id)
    //     }
    //
    //     fn list_jobs() -> Vec<(Vec<u8>, pallet_swarm_media::JobStatusRecord)> {
    //         pallet_swarm_media::Pallet::<Runtime>::list_jobs()
    //             .into_iter()
    //             .map(|(k, v)| (k.into_inner(), v))
    //             .collect()
    //     }
    // }

    // Note: SwarmEvolution pallet doesn't declare a runtime API yet.
    // The helper methods can be accessed directly via pallet_swarm_evolution::Pallet::<Runtime>

    impl frame_system_rpc_runtime_api::AccountNonceApi<Block, AccountId, Index> for Runtime {
        fn account_nonce(account: AccountId) -> Index {
            System::account_nonce(account)
        }
    }

    impl pallet_transaction_payment_rpc_runtime_api::TransactionPaymentApi<Block, Balance> for Runtime {
        fn query_info(
            uxt: <Block as BlockT>::Extrinsic,
            len: u32,
        ) -> pallet_transaction_payment_rpc_runtime_api::RuntimeDispatchInfo<Balance> {
            TransactionPayment::query_info(uxt, len)
        }

        fn query_fee_details(
            uxt: <Block as BlockT>::Extrinsic,
            len: u32,
        ) -> pallet_transaction_payment::FeeDetails<Balance> {
            TransactionPayment::query_fee_details(uxt, len)
        }

        fn query_weight_to_fee(weight: Weight) -> Balance {
            TransactionPayment::weight_to_fee(weight)
        }

        fn query_length_to_fee(length: u32) -> Balance {
            TransactionPayment::length_to_fee(length)
        }
    }

    impl pallet_transaction_payment_rpc_runtime_api::TransactionPaymentCallApi<Block, Balance, RuntimeCall>
        for Runtime
    {
        fn query_call_info(
            call: RuntimeCall,
            len: u32,
        ) -> pallet_transaction_payment::RuntimeDispatchInfo<Balance> {
            TransactionPayment::query_call_info(call, len)
        }

        fn query_call_fee_details(
            call: RuntimeCall,
            len: u32,
        ) -> pallet_transaction_payment::FeeDetails<Balance> {
            TransactionPayment::query_call_fee_details(call, len)
        }

        fn query_weight_to_fee(weight: Weight) -> Balance {
            TransactionPayment::weight_to_fee(weight)
        }

        fn query_length_to_fee(length: u32) -> Balance {
            TransactionPayment::length_to_fee(length)
        }
    }

    impl sp_consensus_aura::AuraApi<Block, sp_consensus_aura::sr25519::AuthorityId> for Runtime {
        fn slot_duration() -> sp_consensus_aura::SlotDuration {
            sp_consensus_aura::SlotDuration::from_millis(Aura::slot_duration())
        }

        fn authorities() -> Vec<sp_consensus_aura::sr25519::AuthorityId> {
            pallet_aura::Authorities::<Runtime>::get().into_inner()
        }
    }

    impl sp_consensus_grandpa::GrandpaApi<Block> for Runtime {
        fn grandpa_authorities() -> sp_consensus_grandpa::AuthorityList {
            Grandpa::grandpa_authorities()
        }

        fn current_set_id() -> sp_consensus_grandpa::SetId {
            Grandpa::current_set_id()
        }

        fn submit_report_equivocation_unsigned_extrinsic(
            _equivocation_proof: sp_consensus_grandpa::EquivocationProof<
                <Block as BlockT>::Hash,
                sp_runtime::traits::NumberFor<Block>,
            >,
            _key_owner_proof: sp_consensus_grandpa::OpaqueKeyOwnershipProof,
        ) -> Option<()> {
            None
        }

        fn generate_key_ownership_proof(
            _set_id: sp_consensus_grandpa::SetId,
            _authority_id: sp_consensus_grandpa::AuthorityId,
        ) -> Option<sp_consensus_grandpa::OpaqueKeyOwnershipProof> {
            None
        }
    }

    impl sp_block_builder::BlockBuilder<Block> for Runtime {
        fn apply_extrinsic(extrinsic: <Block as BlockT>::Extrinsic) -> sp_runtime::ApplyExtrinsicResult {
            Executive::apply_extrinsic(extrinsic)
        }

        fn finalize_block() -> <Block as BlockT>::Header {
            Executive::finalize_block()
        }

        fn inherent_extrinsics(data: sp_inherents::InherentData) -> Vec<<Block as BlockT>::Extrinsic> {
            data.create_extrinsics()
        }

        fn check_inherents(
            block: Block,
            data: sp_inherents::InherentData,
        ) -> sp_inherents::CheckInherentsResult {
            data.check_extrinsics(&block)
        }
    }
}

#[cfg(feature = "std")]
pub fn atlas_kernel_default_assets() -> Vec<(AssetId, Vec<u8>, u8)> {
    vec![
        (0, b"ATLAS".to_vec(), 12),
        (1, b"ETH".to_vec(), 18),
        (2, b"SOL".to_vec(), 9),
        (3, b"USDC".to_vec(), 6),
    ]
}
