//! Autogenerated weights for pallet_audit_governance
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2025-01-01, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `atlas-sphere`, CPU: `Intel(R) Xeon(R) CPU @ 2.80GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{
	traits::Get,
	weights::{Weight, constants::RocksDbWeight as DbWeight},
};
use core::marker::PhantomData;

/// Weight functions needed for pallet_audit_governance.
pub trait WeightInfo {
	fn submit_proposal() -> Weight;
	fn vote_on_proposal() -> Weight;
	fn execute_proposal() -> Weight;
	fn cancel_proposal() -> Weight;
	fn update_audit_parameters() -> Weight;
	fn set_audit_threshold() -> Weight;
	fn create_audit_schedule() -> Weight;
	fn perform_audit() -> Weight;
	fn approve_audit() -> Weight;
	fn register_auditor() -> Weight;
	fn remove_auditor() -> Weight;
}

/// Weights for pallet_audit_governance using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);

impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn submit_proposal() -> Weight {
		Weight::from_parts(75_000_000, 13000)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	fn vote_on_proposal() -> Weight {
		Weight::from_parts(50_000_000, 8000)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	fn execute_proposal() -> Weight {
		Weight::from_parts(100_000_000, 15000)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	fn cancel_proposal() -> Weight {
		Weight::from_parts(40_000_000, 6000)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	fn update_audit_parameters() -> Weight {
		Weight::from_parts(30_000_000, 4000)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	fn set_audit_threshold() -> Weight {
		Weight::from_parts(30_000_000, 4000)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	fn create_audit_schedule() -> Weight {
		Weight::from_parts(60_000_000, 10000)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	fn perform_audit() -> Weight {
		Weight::from_parts(150_000_000, 25000)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	fn approve_audit() -> Weight {
		Weight::from_parts(50_000_000, 8000)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	fn register_auditor() -> Weight {
		Weight::from_parts(40_000_000, 6000)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	fn remove_auditor() -> Weight {
		Weight::from_parts(35_000_000, 5000)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests, implement the old interface.
impl WeightInfo for () {
	fn submit_proposal() -> Weight {
		Weight::from_parts(75_000_000, 13000)
	}
	fn vote_on_proposal() -> Weight {
		Weight::from_parts(50_000_000, 8000)
	}
	fn execute_proposal() -> Weight {
		Weight::from_parts(100_000_000, 15000)
	}
	fn cancel_proposal() -> Weight {
		Weight::from_parts(40_000_000, 6000)
	}
	fn update_audit_parameters() -> Weight {
		Weight::from_parts(30_000_000, 4000)
	}
	fn set_audit_threshold() -> Weight {
		Weight::from_parts(30_000_000, 4000)
	}
	fn create_audit_schedule() -> Weight {
		Weight::from_parts(60_000_000, 10000)
	}
	fn perform_audit() -> Weight {
		Weight::from_parts(150_000_000, 25000)
	}
	fn approve_audit() -> Weight {
		Weight::from_parts(50_000_000, 8000)
	}
	fn register_auditor() -> Weight {
		Weight::from_parts(40_000_000, 6000)
	}
	fn remove_auditor() -> Weight {
		Weight::from_parts(35_000_000, 5000)
	}
}
